
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry txtPantalla;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button btnSigno;

	private global::Gtk.Button btnLimpiar;

	private global::Gtk.Button btnRetroceder;

	private global::Gtk.Button btnRaiz;

	private global::Gtk.Button btnExponente;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button btn7;

	private global::Gtk.Button btn8;

	private global::Gtk.Button btn9;

	private global::Gtk.Button btnDiv;

	private global::Gtk.Button btnSeno;

	private global::Gtk.Button btnPi;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btn4;

	private global::Gtk.Button btn5;

	private global::Gtk.Button btn6;

	private global::Gtk.Button btnMult;

	private global::Gtk.Button btnCoseno;

	private global::Gtk.Button btnE;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btn1;

	private global::Gtk.Button btn2;

	private global::Gtk.Button btn3;

	private global::Gtk.Button btnResta;

	private global::Gtk.Button btnTangente;

	private global::Gtk.Button btnLOG;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button btnPunto;

	private global::Gtk.Button btnCero;

	private global::Gtk.Button btnInversa;

	private global::Gtk.Button btnMas;

	private global::Gtk.Button btnIgual;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 300;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(12));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtPantalla = new global::Gtk.Entry();
		this.txtPantalla.HeightRequest = 40;
		this.txtPantalla.CanFocus = true;
		this.txtPantalla.Name = "txtPantalla";
		this.txtPantalla.IsEditable = false;
		this.txtPantalla.InvisibleChar = '•';
		this.vbox1.Add(this.txtPantalla);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtPantalla]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSigno = new global::Gtk.Button();
		this.btnSigno.WidthRequest = 40;
		this.btnSigno.CanFocus = true;
		this.btnSigno.Name = "btnSigno";
		this.btnSigno.UseUnderline = true;
		this.btnSigno.Label = global::Mono.Unix.Catalog.GetString("+/-");
		this.hbox1.Add(this.btnSigno);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSigno]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnLimpiar = new global::Gtk.Button();
		this.btnLimpiar.WidthRequest = 40;
		this.btnLimpiar.HeightRequest = 40;
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString("CLS");
		this.hbox1.Add(this.btnLimpiar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnLimpiar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRetroceder = new global::Gtk.Button();
		this.btnRetroceder.WidthRequest = 83;
		this.btnRetroceder.CanFocus = true;
		this.btnRetroceder.Name = "btnRetroceder";
		this.btnRetroceder.UseUnderline = true;
		this.btnRetroceder.Label = global::Mono.Unix.Catalog.GetString("DEL");
		this.hbox1.Add(this.btnRetroceder);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnRetroceder]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRaiz = new global::Gtk.Button();
		this.btnRaiz.WidthRequest = 40;
		this.btnRaiz.CanFocus = true;
		this.btnRaiz.Name = "btnRaiz";
		this.btnRaiz.UseUnderline = true;
		this.btnRaiz.Label = global::Mono.Unix.Catalog.GetString("Raiz");
		this.hbox1.Add(this.btnRaiz);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnRaiz]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnExponente = new global::Gtk.Button();
		this.btnExponente.CanFocus = true;
		this.btnExponente.Name = "btnExponente";
		this.btnExponente.UseUnderline = true;
		this.btnExponente.Label = global::Mono.Unix.Catalog.GetString("EXP");
		this.hbox1.Add(this.btnExponente);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnExponente]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn7 = new global::Gtk.Button();
		this.btn7.WidthRequest = 40;
		this.btn7.HeightRequest = 40;
		this.btn7.CanFocus = true;
		this.btn7.Name = "btn7";
		this.btn7.UseUnderline = true;
		this.btn7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox2.Add(this.btn7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btn7]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn8 = new global::Gtk.Button();
		this.btn8.WidthRequest = 40;
		this.btn8.CanFocus = true;
		this.btn8.Name = "btn8";
		this.btn8.UseUnderline = true;
		this.btn8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox2.Add(this.btn8);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btn8]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn9 = new global::Gtk.Button();
		this.btn9.WidthRequest = 40;
		this.btn9.CanFocus = true;
		this.btn9.Name = "btn9";
		this.btn9.UseUnderline = true;
		this.btn9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox2.Add(this.btn9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btn9]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnDiv = new global::Gtk.Button();
		this.btnDiv.WidthRequest = 40;
		this.btnDiv.CanFocus = true;
		this.btnDiv.Name = "btnDiv";
		this.btnDiv.UseUnderline = true;
		this.btnDiv.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox2.Add(this.btnDiv);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnDiv]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnSeno = new global::Gtk.Button();
		this.btnSeno.CanFocus = true;
		this.btnSeno.Name = "btnSeno";
		this.btnSeno.UseUnderline = true;
		this.btnSeno.Label = global::Mono.Unix.Catalog.GetString("SIN");
		this.hbox2.Add(this.btnSeno);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSeno]));
		w12.Position = 4;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnPi = new global::Gtk.Button();
		this.btnPi.WidthRequest = 40;
		this.btnPi.CanFocus = true;
		this.btnPi.Name = "btnPi";
		this.btnPi.UseUnderline = true;
		this.btnPi.Label = global::Mono.Unix.Catalog.GetString("PI");
		this.hbox2.Add(this.btnPi);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnPi]));
		w13.Position = 5;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btn4 = new global::Gtk.Button();
		this.btn4.WidthRequest = 40;
		this.btn4.HeightRequest = 40;
		this.btn4.CanFocus = true;
		this.btn4.Name = "btn4";
		this.btn4.UseUnderline = true;
		this.btn4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox3.Add(this.btn4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btn4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btn5 = new global::Gtk.Button();
		this.btn5.WidthRequest = 40;
		this.btn5.CanFocus = true;
		this.btn5.Name = "btn5";
		this.btn5.UseUnderline = true;
		this.btn5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox3.Add(this.btn5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btn5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btn6 = new global::Gtk.Button();
		this.btn6.WidthRequest = 40;
		this.btn6.CanFocus = true;
		this.btn6.Name = "btn6";
		this.btn6.UseUnderline = true;
		this.btn6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox3.Add(this.btn6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btn6]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnMult = new global::Gtk.Button();
		this.btnMult.WidthRequest = 40;
		this.btnMult.CanFocus = true;
		this.btnMult.Name = "btnMult";
		this.btnMult.UseUnderline = true;
		this.btnMult.Label = global::Mono.Unix.Catalog.GetString("X");
		this.hbox3.Add(this.btnMult);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnMult]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnCoseno = new global::Gtk.Button();
		this.btnCoseno.CanFocus = true;
		this.btnCoseno.Name = "btnCoseno";
		this.btnCoseno.UseUnderline = true;
		this.btnCoseno.Label = global::Mono.Unix.Catalog.GetString("COS");
		this.hbox3.Add(this.btnCoseno);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnCoseno]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnE = new global::Gtk.Button();
		this.btnE.WidthRequest = 40;
		this.btnE.CanFocus = true;
		this.btnE.Name = "btnE";
		this.btnE.UseUnderline = true;
		this.btnE.Label = global::Mono.Unix.Catalog.GetString("E");
		this.hbox3.Add(this.btnE);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnE]));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn1 = new global::Gtk.Button();
		this.btn1.WidthRequest = 40;
		this.btn1.HeightRequest = 40;
		this.btn1.CanFocus = true;
		this.btn1.Name = "btn1";
		this.btn1.UseUnderline = true;
		this.btn1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox4.Add(this.btn1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn1]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn2 = new global::Gtk.Button();
		this.btn2.WidthRequest = 40;
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox4.Add(this.btn2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn3 = new global::Gtk.Button();
		this.btn3.WidthRequest = 40;
		this.btn3.CanFocus = true;
		this.btn3.Name = "btn3";
		this.btn3.UseUnderline = true;
		this.btn3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox4.Add(this.btn3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn3]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnResta = new global::Gtk.Button();
		this.btnResta.WidthRequest = 40;
		this.btnResta.CanFocus = true;
		this.btnResta.Name = "btnResta";
		this.btnResta.UseUnderline = true;
		this.btnResta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox4.Add(this.btnResta);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnResta]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnTangente = new global::Gtk.Button();
		this.btnTangente.CanFocus = true;
		this.btnTangente.Name = "btnTangente";
		this.btnTangente.UseUnderline = true;
		this.btnTangente.Label = global::Mono.Unix.Catalog.GetString("TAN");
		this.hbox4.Add(this.btnTangente);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnTangente]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnLOG = new global::Gtk.Button();
		this.btnLOG.WidthRequest = 40;
		this.btnLOG.CanFocus = true;
		this.btnLOG.Name = "btnLOG";
		this.btnLOG.UseUnderline = true;
		this.btnLOG.Label = global::Mono.Unix.Catalog.GetString("Log10");
		this.hbox4.Add(this.btnLOG);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnLOG]));
		w27.Position = 5;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w28.Position = 4;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.WidthRequest = 40;
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnPunto = new global::Gtk.Button();
		this.btnPunto.WidthRequest = 40;
		this.btnPunto.HeightRequest = 40;
		this.btnPunto.CanFocus = true;
		this.btnPunto.Name = "btnPunto";
		this.btnPunto.UseUnderline = true;
		this.btnPunto.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox5.Add(this.btnPunto);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnPunto]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnCero = new global::Gtk.Button();
		this.btnCero.WidthRequest = 40;
		this.btnCero.CanFocus = true;
		this.btnCero.Name = "btnCero";
		this.btnCero.UseUnderline = true;
		this.btnCero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox5.Add(this.btnCero);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnCero]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnInversa = new global::Gtk.Button();
		this.btnInversa.WidthRequest = 40;
		this.btnInversa.CanFocus = true;
		this.btnInversa.Name = "btnInversa";
		this.btnInversa.UseUnderline = true;
		this.btnInversa.Label = global::Mono.Unix.Catalog.GetString("INV");
		this.hbox5.Add(this.btnInversa);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnInversa]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnMas = new global::Gtk.Button();
		this.btnMas.WidthRequest = 40;
		this.btnMas.CanFocus = true;
		this.btnMas.Name = "btnMas";
		this.btnMas.UseUnderline = true;
		this.btnMas.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox5.Add(this.btnMas);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnMas]));
		w32.Position = 3;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnIgual = new global::Gtk.Button();
		this.btnIgual.WidthRequest = 87;
		this.btnIgual.CanFocus = true;
		this.btnIgual.Name = "btnIgual";
		this.btnIgual.UseUnderline = true;
		this.btnIgual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox5.Add(this.btnIgual);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnIgual]));
		w33.Position = 4;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w34.Position = 5;
		w34.Expand = false;
		w34.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 509;
		this.DefaultHeight = 342;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnSigno.Clicked += new global::System.EventHandler(this.OnBtnSignoClicked);
		this.btnLimpiar.Clicked += new global::System.EventHandler(this.OnBtnLimpiarClicked);
		this.btnRetroceder.Clicked += new global::System.EventHandler(this.OnBtnRetrocederClicked);
		this.btnRaiz.Clicked += new global::System.EventHandler(this.OnBtnRaizClicked);
		this.btnExponente.Clicked += new global::System.EventHandler(this.OnBtnExponenteClicked);
		this.btn7.Clicked += new global::System.EventHandler(this.OnBtn7Clicked);
		this.btn8.Clicked += new global::System.EventHandler(this.OnBtn8Clicked);
		this.btn9.Clicked += new global::System.EventHandler(this.OnBtn9Clicked);
		this.btnDiv.Clicked += new global::System.EventHandler(this.OnBtnDivClicked);
		this.btnSeno.Clicked += new global::System.EventHandler(this.OnBtnSenoClicked);
		this.btnPi.Clicked += new global::System.EventHandler(this.OnBtnPiClicked);
		this.btn4.Clicked += new global::System.EventHandler(this.OnBtn4Clicked);
		this.btn5.Clicked += new global::System.EventHandler(this.OnBtn5Clicked);
		this.btn6.Clicked += new global::System.EventHandler(this.OnBtn6Clicked);
		this.btnMult.Clicked += new global::System.EventHandler(this.OnBtnMultClicked);
		this.btnCoseno.Clicked += new global::System.EventHandler(this.OnBtnCosenoClicked);
		this.btnE.Clicked += new global::System.EventHandler(this.OnBtnEClicked);
		this.btn1.Clicked += new global::System.EventHandler(this.OnBtn1Clicked);
		this.btn2.Clicked += new global::System.EventHandler(this.OnBtn2Clicked);
		this.btn3.Clicked += new global::System.EventHandler(this.OnBtn3Clicked);
		this.btnResta.Clicked += new global::System.EventHandler(this.OnBtnRestaClicked);
		this.btnTangente.Clicked += new global::System.EventHandler(this.OnBtnTangenteClicked);
		this.btnLOG.Clicked += new global::System.EventHandler(this.OnBtnLOGClicked);
		this.btnPunto.Clicked += new global::System.EventHandler(this.OnBtnPuntoClicked);
		this.btnCero.Clicked += new global::System.EventHandler(this.OnBtnCeroClicked);
		this.btnInversa.Clicked += new global::System.EventHandler(this.OnBtnInversaClicked);
		this.btnMas.Clicked += new global::System.EventHandler(this.OnBtnMasClicked);
		this.btnIgual.Clicked += new global::System.EventHandler(this.OnBtnIgualClicked);
	}
}
